enum GameLaunchType
{
	CLIENT = 1,
	SERVER = 2,
	BOTH   = 3, //CLIENT | SERVER
	OFFLINE= 8,
	EDITOR = 24 // OFFLINE | 16
};

enum DayZEnvironmentType
{
	//! Custom must be first
	CUSTOM,
	
	STABLE,
	EXPERIMENTAL,
};

// int.MAX prevents 'none' from showing up
enum YesNo
{
	NO = 0,
	YES = 2147483647,
};

enum BuilderType
{
	PBO_PROJECT = 0,
	ADDON_BUILDER,
};

class LaunchSettings: SerializableBase
{
	static const int VERSION = 7;
	
	static const string CLIENT_PROFILE_NAME = "client";
	static const string CLIENT2_PROFILE_NAME = "client2";
	static const string SERVER_PROFILE_NAME = "server";
	static const string BASE_LAUNCH_PARAMS = "-newErrorsAreWarnings=1 -doLogs -adminlog -scriptDebug=true -profile -resizeable -no_preload_vehicles -idleRender";
	
	protected string m_CurrentFileLocation;
	
	[Attribute("", "editbox", "Repository Directory")]
	string Repository;
		
	[Attribute("", "combobox", "Launch", "", ParamEnumArray.FromEnum(GameLaunchType) )]
	int LaunchType;
	
	[Attribute("", "combobox", "Environment", "", ParamEnumArray.FromEnum(DayZEnvironmentType) )]
	int EnvironmentType;
	
	[Attribute("", "editbox", "Custom game directory")]
	string CustomGameDirectory;
	
	[Attribute("", "editbox", "Executable")]
	string Executable;
	
	[Attribute("", "editbox", "Map")]
	string Map;
		
	[Attribute("", "combobox", "Enable File Patching", "", ParamEnumArray.FromEnum(YesNo) )]
	bool FilePatching;	
	
	[Attribute("", "combobox", "Enable Deloginator", "", ParamEnumArray.FromEnum(YesNo) )]
	bool Deloginator;
	
	[Attribute("", "combobox", "Auto Close Game", "", ParamEnumArray.FromEnum(YesNo) )]
	bool AutoClose;
	
	[Attribute("", "combobox", "Disable Mod", "", ParamEnumArray.FromEnum(YesNo) )]
	bool DisableMod;
	
	[Attribute("", "editbox", "Port")]
	int Port;
	
	string JoinAddress, JoinPassword;
	int JoinPort;
	
	[Attribute("", "editbox", "Profile Directory (will be auto generated by the build tools)")]
	string Profiles;		
	
	[Attribute("", "editbox", "Mission Directory (will be auto generated by the build tools)")]
	string Missions;		
	
	[Attribute("", "editbox", "Mod Directory (will be auto generated by the build tools)")]
	string Mods;
	
	[Attribute("", "combobox", "Enable Sandboxie", "", ParamEnumArray.FromEnum(YesNo) )]
	int SandboxieEnabled;

	[Attribute("", "editbox", "Sandboxie Box (Steam Box)")]
	string SandboxieBoxPath;

	[Attribute("", "editbox", "Sandboxie Box (Program Files Path, Contains Start.exe)")]
	string SandboxieInstallPath;
			
	[Attribute("", "editbox", "Server password")]
	string ServerPassword;	
	
	[Attribute("", "combobox", "Disable Mod", "", ParamEnumArray.FromEnum(YesNo) )]
	bool EnableHive;
		
	void Save(string file = "")
	{
		if (file == string.Empty) {
			file = m_CurrentFileLocation;
		}

		FileSerializer serializer = new FileSerializer();
		if (!serializer.Open(file, FileMode.WRITE)) {
			return;
		}
		
		int version = VERSION;
		
		Executable.Replace(PluginDialogBase.Path.SEPERATOR, PluginDialogBase.Path.SEPERATOR_ALT);

		serializer.Write(version);
		Write(serializer, version);

		serializer.Close();
	}
	
	static LaunchSettings Load(string file)
	{		
		LaunchSettings settings = new LaunchSettings();
		settings.m_CurrentFileLocation = file;
		settings.LaunchType = GameLaunchType.BOTH;
		settings.Profiles = "P:\\Profiles";
		settings.Missions = "P:\\Missions";
		settings.Mods = "P:\\Mods";
		settings.Executable = "DayZDiag_x64.exe";
		settings.EnvironmentType = DayZEnvironmentType.STABLE;
		settings.CustomGameDirectory = "";
		settings.SandboxieEnabled = false;
		settings.SandboxieBoxPath = "";
		settings.SandboxieInstallPath = "";
		settings.Map = "ChernarusPlus";
		settings.FilePatching = true;
		settings.Deloginator = true;
		settings.AutoClose = true;
		settings.Port = 2302;
		settings.JoinAddress = "127.0.0.1";

		if (!FileExist(file)) {
			settings.Save(file);
			return settings;
		}
		
		FileSerializer serializer = new FileSerializer();
		if (!serializer.Open(file, FileMode.READ)) {
			return null;
		}
		
		int version;
		if (!serializer.Read(version)) {
			return null;
		}

		if (version > VERSION) {
			Error("Invalid file version read!");
			return null;
		}

		if (!settings.Read(serializer, version)) {
			return null;
		}
		
		serializer.Close();
		return settings;
	}
	
	override void Write(Serializer serializer, int version)
	{
		serializer.Write(Repository);
		serializer.Write(Profiles);
		serializer.Write(Missions);
		serializer.Write(Mods);
		serializer.Write(LaunchType);
		serializer.Write(ServerPassword);
		serializer.Write(Map);
		serializer.Write(FilePatching);
		serializer.Write(AutoClose);
		serializer.Write(DisableMod);
		serializer.Write(Port);
		serializer.Write(JoinAddress);
		serializer.Write(Executable);
		serializer.Write(EnvironmentType);
		serializer.Write(CustomGameDirectory);
		serializer.Write(SandboxieEnabled);
		serializer.Write(SandboxieBoxPath);
		serializer.Write(SandboxieInstallPath);
		serializer.Write(EnableHive);
	}
	
	override bool Read(Serializer serializer, int version)
	{		
		if (!serializer.Read(Repository)) {
			return false;
		}
		
		if (!serializer.Read(Profiles)) {
			return false;
		}		
		
		if (!serializer.Read(Missions)) {
			return false;
		}		
		
		if (!serializer.Read(Mods)) {
			return false;
		}
			
		if (!serializer.Read(LaunchType)) {
			return false;
		}
											
		if (!serializer.Read(ServerPassword)) {
			return false;
		}		
				
		if (!serializer.Read(Map)) {
			return false;
		}		
		
		if (!serializer.Read(FilePatching)) {
			return false;
		}		
		
		if (!serializer.Read(AutoClose)) {
			return false;
		}		
		
		if (version < 2) {
			return true;
		}
		
		if (!serializer.Read(DisableMod)) {
			return false;
		}		
		
		if (version < 3) {
			return true;
		}
		
		if (!serializer.Read(Port)) {
			return false;
		}
		
		if (version < 4) {
			return true;
		}
		
		if (!serializer.Read(JoinAddress)) {
			return false;
		}
		
		if (version < 5) {
			return true;
		}
		
		if (!serializer.Read(Executable)) {
			return false;
		}
		
		if (version < 6) {
			return true;
		}
		
		if (!serializer.Read(EnvironmentType)) {
			return false;
		}
		
		if (!serializer.Read(CustomGameDirectory)) {
			return false;
		}

		if (version < 7) {
			return true;
		}
		
		if (!serializer.Read(SandboxieEnabled)) {
			return false;
		}
		
		if (!serializer.Read(SandboxieBoxPath)) {
			return false;
		}

		if (!serializer.Read(SandboxieInstallPath)) {
			return false;
		}
		
		if (version < 8) {
			return true;
		}
		
		if (!serializer.Read(EnableHive)) {
			return false;
		}
		
		return true;
	}
	
	[ButtonAttribute("Ok", true)]
	void Ok()
	{
		Save(m_CurrentFileLocation);
	}
	
	[ButtonAttribute("Cancel")]
	void Cancel()
	{
	}
	
	string GetExecutableName()
	{
		if (FileExist(Executable))
		{
			string exec = Executable;
			int index = exec.LastIndexOf(PluginDialogBase.Path.SEPERATOR_ALT);
			int size = exec.Length();
			
			if (index > 0)
			{
				exec = exec.Substring(index + 1, size - (index + 1));
			}
			
			return exec;
		}
		return Executable;
	}
}
