enum WidgetAnimatorProperty
{
	POSITION_X 	= 1,
	POSITION_Y 	= 2,

	SIZE_W		= 4,
	SIZE_H		= 8,

	ROTATION_X	= 16, // Roll
	ROTATION_Y	= 32, // Pitch
	ROTATION_Z	= 64, // Yaw

	// all color values are in float from 0...1
	COLOR_A		= 128, 
	
	COLOR_R		= 256,
	COLOR_G		= 512,
	COLOR_B		= 1024,
	
	COLOR_H		= 2048,
	COLOR_S		= 4096,
	COLOR_V		= 8192,
	
	EXACT_TEXT 	= 16384,
	SIZE_EXACT_W = 32768,
	SIZE_EXACT_H = 65536,
	LINEAR_COLOR = 1920 // A, R, G, B
};

enum WidgetAnimatorEasing
{
	NONE = 0,

	EASE_IN_SINE,
	EASE_OUT_SINE,
	EASE_INOUT_SINE,

	EASE_IN_QUAD,
	EASE_OUT_QUAD,
	EASE_INOUT_QUAD,

	EASE_IN_CUBIC,
	EASE_OUT_CUBIC,
	EASE_INOUT_CUBIC,

	EASE_IN_QUART,
	EASE_OUT_QUART,
	EASE_INOUT_QUART,

	EASE_IN_QUINT,
	EASE_OUT_QUINT,
	EASE_INOUT_QUINT,

	EASE_IN_EXPONENTIAL,
	EASE_OUT_EXPONENTIAL,
	EASE_INOUT_EXPONENTIAL,

	EASE_IN_CIRC,
	EASE_OUT_CIRC,
	EASE_INOUT_CIRC,

	EASE_IN_BACK,
	EASE_OUT_BACK,
	EASE_INOUT_BACK,

	EASE_IN_ELASTIC,
	EASE_OUT_ELASTIC,
	EASE_INOUT_ELASTIC,
	
	EASE_IN_BOUNCE,
	EASE_OUT_BOUNCE,
	EASE_INOUT_BOUNCE,
};